alias home='cd $HOME'
alias dt='cd /c/users/allan/desktop'
alias dc='cd /c/users/allan/documents'
alias dl='cd /c/users/allan/downloads'
alias htdocs='cd /d/xampp/htdocs'
alias subl='c:Program\ Files/Sublime\ Text\ 3/sublime_text.exe'
